// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpacdeyavjodixeymzpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYWNkZXlhdmpvZGl4ZXltenBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MzU1OTcsImV4cCI6MjA5MTUxMTU5N30.9HFQeLT6nDjJqSSgBlyI0GWP62Lq276p0MzRC184V-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});